ntrpg:
  enabled: true
  skip_if_already: false
  icon: iron_axe
  name: ntrpg-guis
  permission: ia.menu.ntrpg
  items:
    - ntrpg:ntrpg_back
    - ntrpg:ntrpg_back
    - ntrpg:ntrpg_confirm
    - ntrpg:ntrpg_agi
    - ntrpg:ntrpg_con
    - ntrpg:ntrpg_dex
    - ntrpg:ntrpg_int
    - ntrpg:ntrpg_str
    - ntrpg:ntrpg_wis
    - ntrpg:char_armor
    - ntrpg:char_weapons
    - ntrpg:char_attributes
    - ntrpg:char_spellbook
    - ntrpg:char_class_slot
    - ntrpg:classes_proffesion
    - ntrpg:class_dependencies
    - ntrpg:skill_tree
    - ntrpg:attributes
    - ntrpg:skilltree_mode_a
    - ntrpg:skilltree_mode_b
    - ntrpg:skilltree_arrow_u
    - ntrpg:skilltree_arrow_d
    - ntrpg:skilltree_arrow_l
    - ntrpg:skilltree_arrow_r
    - ntrpg:ntrpg_skill_connection_horizontal
    - ntrpg:ntrpg_skill_connection_vertical
    - ntrpg:ntrpg_skill_connection_arrow_left
    - ntrpg:ntrpg_skill_connection_arrow_right
    - ntrpg:ntrpg_skill_connection_arrow_up
    - ntrpg:ntrpg_skill_connection_arrow_down
    - ntrpg:ntrpg_skill_connection_cross
    - ntrpg:ntrpg_skill_connection_down_left
    - ntrpg:ntrpg_skill_connection_up_left
    - ntrpg:ntrpg_skill_connection_down_right
    - ntrpg:ntrpg_skill_connection_up_right
    - ntrpg:ntrpg_skill_connection_t_no_down
    - ntrpg:ntrpg_skill_connection_t_no_up
    - ntrpg:ntrpg_skill_connection_t_no_right
    - ntrpg:ntrpg_skill_connection_t_no_left