--@author:NeumimTo
--@date:04.09.2018
--@note:Initial setup
--@id:init-db
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_CLASSID START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_SKILLID START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_ATTRIBUTE_ID START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_CHAR_BASE START WITH 1 BELONGS_TO_TABLE;

CREATE CACHED TABLE PUBLIC.RPG_CHARACTER_ATTRIBUTE(
    ATTRIBUTE_ID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_ATTRIBUTE_ID) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_ATTRIBUTE_ID,
    LEVEL INTEGER NOT NULL,
    NAME VARCHAR(255),
    CHARACTERID BIGINT NOT NULL
);
ALTER TABLE PUBLIC.RPG_CHARACTER_ATTRIBUTE ADD CONSTRAINT PUBLIC.CONSTRAINT_5 PRIMARY KEY(ATTRIBUTE_ID);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.RPG_CHARACTER_ATTRIBUTE;
CREATE CACHED TABLE PUBLIC.RPG_CHARACTER_BASE(
    CHARACTER_ID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_CHAR_BASE) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_CHAR_BASE,
    CREATED BIGINT,
    UPDATED BIGINT,
    X INTEGER,
    Y INTEGER,
    Z INTEGER,
    ATTRIBUTE_POINTS INTEGER,
    CAN_RESET_SKILLS BOOLEAN,
    CHARACTER_COOLDOWNS TEXT,
    GUILD_ID BIGINT,
    HEALTH_SCALE DOUBLE,
    INFO VARCHAR(255),
    INVENTORY_EQUIP_SLOT_ORDER TEXT,
    LAST_KNOWN_PLAYER_NAME VARCHAR(16),
    LAST_RESET_TIME TIMESTAMP,
    MARKED_FOR_REMOVAL BOOLEAN,
    MESSAGETYPE VARCHAR(255),
    NAME VARCHAR(40),
    PRIMARY_CLASS VARCHAR(255),
    RACE VARCHAR(255),
    USED_ATTRIBUTE_POINTS INTEGER,
    UUID VARCHAR(255),
    VERSION BIGINT,
    WORLD VARCHAR(255)
);
ALTER TABLE PUBLIC.RPG_CHARACTER_BASE ADD CONSTRAINT PUBLIC.CONSTRAINT_A PRIMARY KEY(CHARACTER_ID);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.RPG_CHARACTER_BASE;
CREATE INDEX PUBLIC.IDX_CHAR_BASE_UUID ON PUBLIC.RPG_CHARACTER_BASE(UUID);
CREATE CACHED TABLE PUBLIC.RPG_CHARACTER_CLASS(
    CLASSID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_CLASSID) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_CLASSID,
    EXPERIENCES DOUBLE,
    NAME VARCHAR(255),
    SKILLPOINTS INTEGER,
    USED_SKIL_POINTS INTEGER,
    CHARACTERID BIGINT
);
ALTER TABLE PUBLIC.RPG_CHARACTER_CLASS ADD CONSTRAINT PUBLIC.CONSTRAINT_6 PRIMARY KEY(CLASSID);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.RPG_CHARACTER_CLASS;
CREATE CACHED TABLE PUBLIC.RPG_CHARACTER_SKILL(
    SKILLID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_SKILLID) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_SKILLID,
    CATALOG_ID VARCHAR(255),
    LEVEL INTEGER NOT NULL,
    CHARACTER_ID BIGINT,
    CLASS_ID BIGINT
);
ALTER TABLE PUBLIC.RPG_CHARACTER_SKILL ADD CONSTRAINT PUBLIC.CONSTRAINT_6F PRIMARY KEY(SKILLID);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.RPG_CHARACTER_SKILL;
ALTER TABLE PUBLIC.RPG_CHARACTER_SKILL ADD CONSTRAINT PUBLIC.FK_CHAR_SKILL_CLASS_ID FOREIGN KEY(CLASS_ID) REFERENCES PUBLIC.RPG_CHARACTER_CLASS(CLASSID) NOCHECK;
ALTER TABLE PUBLIC.RPG_CHARACTER_SKILL ADD CONSTRAINT PUBLIC.FK_CHAR_SKILL_CHAR_ID FOREIGN KEY(CHARACTER_ID) REFERENCES PUBLIC.RPG_CHARACTER_BASE(CHARACTER_ID) NOCHECK;
ALTER TABLE PUBLIC.RPG_CHARACTER_CLASS ADD CONSTRAINT PUBLIC.FK_CHAR_CLASS_CHAR_ID FOREIGN KEY(CHARACTERID) REFERENCES PUBLIC.RPG_CHARACTER_BASE(CHARACTER_ID) NOCHECK;
ALTER TABLE PUBLIC.RPG_CHARACTER_ATTRIBUTE ADD CONSTRAINT PUBLIC.FK_CHAR_ATTR_CHAR_ID FOREIGN KEY(CHARACTERID) REFERENCES PUBLIC.RPG_CHARACTER_BASE(CHARACTER_ID) NOCHECK;